tript/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'tript'

urlpatterns = [
    url(r'^$', views.LandingView.as_view(), name='landing'),
    url(r'^logout/', auth_views.LogoutView.as_view(template_name='tript/logout.html'), name='logout'),
    url(r'^login/', views.LoginUserView.as_view(), name='login'),
    url(r'^sign_up/', views.SignUpView.as_view(), name='sign_up'),
    url(r'^dashboard/', views.DashboardView.as_view(), name='dashboard')
]

triptProject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('tript.urls')),
    url(r'^admin/', admin.site.urls),
]

tript/models.py
from django.db import models
from django.contrib import auth

# Create your models here.
class TriptUser(auth.models.User, auth.models.PermissionsMixin):
   ## user = models.OneToOneField(User)
   ## country = models.CharField(max_length=256)
   ## city = models.CharField(max_length=256)

    def __str__(self):
        return self.username

class Trips(models.Model):
    countries = models.CharField(max_length=256)
    cities= models.CharField(max_length=256)

tript/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from tript.models import TriptUser

class UserCreateForm(UserCreationForm):
    #password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model= get_user_model()
        fields = ('username', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Display Name'
        self.fields['email'].label = 'Email'

##class TriptUserForm(forms.ModelForm):
##    class Meta():
##        model = TriptUser
 ##       fields = ('country','city')

tript/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.views import LoginView
from django.views.generic import (TemplateView, DetailView, FormView, ListView, CreateView, DeleteView, UpdateView)
from tript.forms import UserCreateForm#,TriptUserForm
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
class LandingView(TemplateView):
  template_name='landing.html'

class LoginUserView(LoginView):
  template_name='login.html'

class SignUpView(CreateView):
  context_object_name= 'user_create'
  form_class = UserCreateForm
  success_url = reverse_lazy('login')
  template_name='signup.html'

class DashboardView(LoginRequiredMixin,TemplateView):
  template_name='dashboard.html'

tript/templates/tript/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <title>Tript</title>
    <link rel='stylesheet' href="{% static 'css/page.css' %}">
    <link rel='stylesheet' href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=M+PLUS+1p|Ubuntu:700,700i" rel="stylesheet">
  <style>
    * {
        vertical-align: baseline;
        font-weight: inherit;
        font-family: inherit;
        font-style: inherit;
        font-size: 100%;
        border: 0 none;
        outline: 0;
        padding: 0;
        margin: 0;
        box-sizing: border-box;
    }

    body {
        padding: 0px;
    }


    li, dd, blockquote {
    margin-left: 40px;
    }

    table {
    border-collapse: collapse;
    border-spacing: 0;
    }
    </style>
  </head>
<body>
<nav class="navbar">
  <ul>
    {% if user.is_authenticated %}
        <li class="icon" id="icon"><img src="{% static 'media/logo.png' %}" alt="logo" /></li>
        <li><button class="landing-button"><a href="{% url 'tript:logout' %}">Sign out</a></button></li>
    {% else %}
        <li class="icon" id="icon"><img src="{% static 'media/logo.png' %}" alt="logo" /></li>
        <li><button class="landing-button"><a href="{% url 'tript:login' %}">Sign In</a></button></li>
        <li><button class="landing-button"><a href="{% url 'tript:sign_up' %}">Create Account</a></button></li>
    {% endif %}
  </ul>
</nav>
<div></div>
{% block content %}
{% endblock %}
</body>
</html>

tript/templates/tript/dashboard.html
{% extends "tript/base.html" %}
{% block content %}
<h1>This is the dashboard</h1>

{% endblock %}

tript/templates/tript/landing.html
{% extends "tript/base.html" %}
{% load staticfiles %}
{% block content %}
<div class="landing-body">
<main class="landing-titles">
  <div class="titles">
    <h1>Welcome to Tript</h1>
    <h2>Share Your Travels From</h2>
    <h2>Around The World</h2>
    <br/>
    <button class="landing-button">Get Started</button>
  </div>
</main>
</div>
<div class="image-landing">

</div>
{% endblock %}

tript/templates/tript/login.html
{% extends "tript/base.html" %}
{% block content %}
<h1>Login</h1>
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Sign in" />
</form>
{% endblock %}

tript/templates/tript/signup.html
{% extends "tript/base.html" %}
{% block content %}

<h1>Sign Up</h1>
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Sign Up">
</form>
{% endblock %}